name: ❓ Question
description: Ask a question about one of our samples
labels: ['Needs: Triage :mag:', 'type:question']

body:
- type: markdown
  attributes:
    value: |

      Thank you for asking a question! Use the sections below to submit a question **only** if it's related to samples in this repo. 
      
      - Questions that do not follow the below template will automatically be closed
      - Don't use questions to diagnose issues with samples, that's what bug reports are for!
      - All questions are welcome - let us know what's on your mind!
      - This repo is maintained by volunteers. Please be courteous and patient. 🙂
      - Remember to include sufficient details and context.
      - If you have multiple questions please submit them separately so we can track resolution.
      - Screenshots are always helpful (just paste any images right here in the question)
      - If you're trying to start a conversation on a topic, consider using Discussions. We want to close every issue as quickly as possible, but discussions are intended for longer conversations.

- type: input
  id: sample
  validations:
    required: true
  attributes:
    label: Sample
    description: |
        Which sample are you talking about
        
        Use the sample name or URL. 

- type: input
  id: authors
  validations:
    required: true
  attributes:
    label: Author(s)
    description: |
        Who wrote the sample?
        
        Because of the way this repository is configured, samples authors do not get a notification when you create an issue. 
        
        For the section above **@mention any author of the sample**. Authors' GitHub handle can be found on the main sample documentation page, under the "Solution" section. 
        
        Questions without an @mention will automatically be closed, because authors won't get notified.
        
        **NOTE:** Don't @mention the repo maintainers, they already get notified.

- type: textarea
  id: question
  attributes:
    label: Question
    description: What would you like to know?
    placeholder: The more details, the better
  validations:
    required: true